# Generated by Django 4.1.4 on 2022-12-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.AutoField(primary_key=True, serialize=False)),
                ('arrivaltime', models.DateTimeField()),
                ('departuretime', models.DateTimeField()),
                ('economycost', models.FloatField()),
                ('firstclasscost', models.FloatField()),
                ('luxcost', models.FloatField()),
            ],
            options={
                'db_table': 'flight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infoblock',
            fields=[
                ('infoblockid', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.TextField()),
                ('main', models.TextField()),
            ],
            options={
                'db_table': 'infoblock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passportdata',
            fields=[
                ('passportid', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.BooleanField()),
                ('givenname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('dateofissue', models.DateField()),
                ('dateofexpery', models.DateField()),
                ('idnumber', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passportdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('promocodeid', models.AutoField(primary_key=True, serialize=False)),
                ('promocodevalue', models.CharField(max_length=30)),
                ('discount', models.IntegerField()),
                ('usecount', models.IntegerField()),
            ],
            options={
                'db_table': 'promocode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seatsuite',
            fields=[
                ('seatsuiteid', models.AutoField(primary_key=True, serialize=False)),
                ('economytotal', models.IntegerField()),
                ('firstclasstotal', models.IntegerField()),
                ('luxtotal', models.IntegerField()),
                ('economyreserved', models.IntegerField()),
                ('firstclassreserved', models.IntegerField()),
                ('luxreserved', models.IntegerField()),
            ],
            options={
                'db_table': 'seatsuite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('seatclass', models.CharField(max_length=100)),
                ('ticketcost', models.FloatField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trackid', models.AutoField(primary_key=True, serialize=False)),
                ('isinwheel', models.BooleanField()),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('customertype', models.CharField(max_length=100)),
                ('password', models.CharField(db_column='customerpassword', max_length=100)),
                ('passportid', models.ForeignKey(blank=True, db_column='passportid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.passportdata')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
